Add support for keyword arguments
exasol/error-reporting-python pull request #31
Opened 2024-06-06 12:05 UTC by Nicoretti

Fixes #25

2024-06-06 14:29 UTC, ckunki requested changes

2024-06-06 14:29 UTC, ckunki commented on test/unit/named_paramters_test.py
Maybe rename file to `named_parameters_test.py` ?

2024-06-07 07:33 UTC, Nicoretti commented on test/unit/named_paramters_test.py
Fixed thx :+1:

2024-06-07 07:34 UTC, ckunki approved these changes

2024-06-07 07:44 UTC, merged